export async function generateMetadata() {
  return {
    title: 'Next.js',
    description: 'Generated by Next.js',
  };
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // Child layouts must not render <html> or <body> - those are defined in the root layout.
  return <>{children}</>;
}
